// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: churches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChurchMember = `-- name: AddChurchMember :one
INSERT INTO church_members (church_id, user_id, role) VALUES ($1, $2, $3) RETURNING id, church_id, user_id, role, created_at, updated_at
`

type AddChurchMemberParams struct {
	ChurchID pgtype.UUID      `db:"church_id" json:"church_id"`
	UserID   pgtype.UUID      `db:"user_id" json:"user_id"`
	Role     ChurchMemberRole `db:"role" json:"role"`
}

func (q *Queries) AddChurchMember(ctx context.Context, arg AddChurchMemberParams) (ChurchMember, error) {
	row := q.db.QueryRow(ctx, addChurchMember, arg.ChurchID, arg.UserID, arg.Role)
	var i ChurchMember
	err := row.Scan(
		&i.ID,
		&i.ChurchID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createChurch = `-- name: CreateChurch :one
INSERT INTO churches (name, description) VALUES ($1, $2) RETURNING id, name, description, created_at, updated_at
`

type CreateChurchParams struct {
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) CreateChurch(ctx context.Context, arg CreateChurchParams) (Church, error) {
	row := q.db.QueryRow(ctx, createChurch, arg.Name, arg.Description)
	var i Church
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChurch = `-- name: DeleteChurch :exec
DELETE FROM churches WHERE id = $1
`

func (q *Queries) DeleteChurch(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChurch, id)
	return err
}

const getChurchById = `-- name: GetChurchById :one
SELECT id, name, description, created_at, updated_at FROM churches WHERE id = $1
`

func (q *Queries) GetChurchById(ctx context.Context, id pgtype.UUID) (Church, error) {
	row := q.db.QueryRow(ctx, getChurchById, id)
	var i Church
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChurchMembers = `-- name: ListChurchMembers :many
SELECT
    cm.id, cm.church_id, cm.user_id, cm.role, cm.created_at, cm.updated_at,
    u.username,
    u.email,
    u.id AS user_id
FROM church_members cm
JOIN users u ON u.id = cm.user_id
WHERE cm.church_id = $1
ORDER BY cm.created_at ASC
`

type ListChurchMembersRow struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	ChurchID  pgtype.UUID        `db:"church_id" json:"church_id"`
	UserID    pgtype.UUID        `db:"user_id" json:"user_id"`
	Role      ChurchMemberRole   `db:"role" json:"role"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Username  string             `db:"username" json:"username"`
	Email     string             `db:"email" json:"email"`
	UserID_2  pgtype.UUID        `db:"user_id_2" json:"user_id_2"`
}

func (q *Queries) ListChurchMembers(ctx context.Context, churchID pgtype.UUID) ([]ListChurchMembersRow, error) {
	rows, err := q.db.Query(ctx, listChurchMembers, churchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChurchMembersRow{}
	for rows.Next() {
		var i ListChurchMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.ChurchID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.Email,
			&i.UserID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChurches = `-- name: ListChurches :many
SELECT id, name, description, created_at, updated_at FROM churches ORDER BY name
`

func (q *Queries) ListChurches(ctx context.Context) ([]Church, error) {
	rows, err := q.db.Query(ctx, listChurches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Church{}
	for rows.Next() {
		var i Church
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserChurches = `-- name: ListUserChurches :many
SELECT
    c.name AS church_name,
    c.id AS church_id,
    cm.role AS member_role
FROM church_members cm
JOIN churches c ON c.id = cm.church_id
WHERE cm.user_id = $1
ORDER BY cm.created_at ASC
`

type ListUserChurchesRow struct {
	ChurchName string           `db:"church_name" json:"church_name"`
	ChurchID   pgtype.UUID      `db:"church_id" json:"church_id"`
	MemberRole ChurchMemberRole `db:"member_role" json:"member_role"`
}

func (q *Queries) ListUserChurches(ctx context.Context, userID pgtype.UUID) ([]ListUserChurchesRow, error) {
	rows, err := q.db.Query(ctx, listUserChurches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserChurchesRow{}
	for rows.Next() {
		var i ListUserChurchesRow
		if err := rows.Scan(&i.ChurchName, &i.ChurchID, &i.MemberRole); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChurch = `-- name: UpdateChurch :one
UPDATE churches SET name = $2, description = $3, updated_at = now() WHERE id = $1 RETURNING id, name, description, created_at, updated_at
`

type UpdateChurchParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Name        string      `db:"name" json:"name"`
	Description string      `db:"description" json:"description"`
}

func (q *Queries) UpdateChurch(ctx context.Context, arg UpdateChurchParams) (Church, error) {
	row := q.db.QueryRow(ctx, updateChurch, arg.ID, arg.Name, arg.Description)
	var i Church
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
