// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mission_ventures.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addVentureMember = `-- name: AddVentureMember :one
INSERT INTO venture_members (
    venture_id,
    user_id,
    role
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, venture_id, user_id, role, created_at, updated_at
`

type AddVentureMemberParams struct {
	VentureID pgtype.UUID       `db:"venture_id" json:"venture_id"`
	UserID    pgtype.UUID       `db:"user_id" json:"user_id"`
	Role      MissionMemberRole `db:"role" json:"role"`
}

func (q *Queries) AddVentureMember(ctx context.Context, arg AddVentureMemberParams) (VentureMember, error) {
	row := q.db.QueryRow(ctx, addVentureMember, arg.VentureID, arg.UserID, arg.Role)
	var i VentureMember
	err := row.Scan(
		&i.ID,
		&i.VentureID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVenture = `-- name: CreateVenture :one
INSERT INTO ventures (
    name,
    description,
    created_by_user_id
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, description, created_by_user_id, created_at, updated_at
`

type CreateVentureParams struct {
	Name            string      `db:"name" json:"name"`
	Description     string      `db:"description" json:"description"`
	CreatedByUserID pgtype.UUID `db:"created_by_user_id" json:"created_by_user_id"`
}

func (q *Queries) CreateVenture(ctx context.Context, arg CreateVentureParams) (Venture, error) {
	row := q.db.QueryRow(ctx, createVenture, arg.Name, arg.Description, arg.CreatedByUserID)
	var i Venture
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVentureByID = `-- name: GetVentureByID :one
SELECT id, name, description, created_by_user_id, created_at, updated_at
FROM ventures
WHERE id = $1
`

func (q *Queries) GetVentureByID(ctx context.Context, id pgtype.UUID) (Venture, error) {
	row := q.db.QueryRow(ctx, getVentureByID, id)
	var i Venture
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVentureMembers = `-- name: ListVentureMembers :many
SELECT id, venture_id, user_id, role, created_at, updated_at
FROM venture_members
WHERE venture_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListVentureMembers(ctx context.Context, ventureID pgtype.UUID) ([]VentureMember, error) {
	rows, err := q.db.Query(ctx, listVentureMembers, ventureID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VentureMember{}
	for rows.Next() {
		var i VentureMember
		if err := rows.Scan(
			&i.ID,
			&i.VentureID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVentures = `-- name: ListVentures :many
SELECT id, name, description, created_by_user_id, created_at, updated_at
FROM ventures
ORDER BY created_at DESC
`

func (q *Queries) ListVentures(ctx context.Context) ([]Venture, error) {
	rows, err := q.db.Query(ctx, listVentures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Venture{}
	for rows.Next() {
		var i Venture
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
