// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: missions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMissionMember = `-- name: AddMissionMember :one
INSERT INTO mission_members (
    mission_id,
    user_id,
    role
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, mission_id, user_id, role, created_at, updated_at
`

type AddMissionMemberParams struct {
	MissionID pgtype.UUID       `db:"mission_id" json:"mission_id"`
	UserID    pgtype.UUID       `db:"user_id" json:"user_id"`
	Role      MissionMemberRole `db:"role" json:"role"`
}

func (q *Queries) AddMissionMember(ctx context.Context, arg AddMissionMemberParams) (MissionMember, error) {
	row := q.db.QueryRow(ctx, addMissionMember, arg.MissionID, arg.UserID, arg.Role)
	var i MissionMember
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.UserID,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const addMissionVenture = `-- name: AddMissionVenture :one
INSERT INTO mission_ventures (
    mission_id,
    venture_id,
    description
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING id, mission_id, venture_id, description, created_at, updated_at
`

type AddMissionVentureParams struct {
	MissionID   pgtype.UUID `db:"mission_id" json:"mission_id"`
	VentureID   pgtype.UUID `db:"venture_id" json:"venture_id"`
	Description string      `db:"description" json:"description"`
}

func (q *Queries) AddMissionVenture(ctx context.Context, arg AddMissionVentureParams) (MissionVenture, error) {
	row := q.db.QueryRow(ctx, addMissionVenture, arg.MissionID, arg.VentureID, arg.Description)
	var i MissionVenture
	err := row.Scan(
		&i.ID,
		&i.MissionID,
		&i.VentureID,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMissionOrganization = `-- name: CreateMissionOrganization :one
INSERT INTO mission_organizations (
    name,
    description
)
VALUES (
    $1,
    $2
)
RETURNING id, name, description, created_at, updated_at
`

type CreateMissionOrganizationParams struct {
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) CreateMissionOrganization(ctx context.Context, arg CreateMissionOrganizationParams) (MissionOrganization, error) {
	row := q.db.QueryRow(ctx, createMissionOrganization, arg.Name, arg.Description)
	var i MissionOrganization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMissionOrganizationByID = `-- name: GetMissionOrganizationByID :one
SELECT id, name, description, created_at, updated_at
FROM mission_organizations
WHERE id = $1
`

func (q *Queries) GetMissionOrganizationByID(ctx context.Context, id pgtype.UUID) (MissionOrganization, error) {
	row := q.db.QueryRow(ctx, getMissionOrganizationByID, id)
	var i MissionOrganization
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMissionMembers = `-- name: ListMissionMembers :many
SELECT id, mission_id, user_id, role, created_at, updated_at
FROM mission_members
WHERE mission_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListMissionMembers(ctx context.Context, missionID pgtype.UUID) ([]MissionMember, error) {
	rows, err := q.db.Query(ctx, listMissionMembers, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MissionMember{}
	for rows.Next() {
		var i MissionMember
		if err := rows.Scan(
			&i.ID,
			&i.MissionID,
			&i.UserID,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissionOrganizations = `-- name: ListMissionOrganizations :many
SELECT id, name, description, created_at, updated_at
FROM mission_organizations
ORDER BY created_at DESC
`

func (q *Queries) ListMissionOrganizations(ctx context.Context) ([]MissionOrganization, error) {
	rows, err := q.db.Query(ctx, listMissionOrganizations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MissionOrganization{}
	for rows.Next() {
		var i MissionOrganization
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissionVentures = `-- name: ListMissionVentures :many
SELECT
    mv.id, mv.mission_id, mv.venture_id, mv.description, mv.created_at, mv.updated_at,
    v.name AS venture_name
FROM mission_ventures mv
JOIN ventures v ON v.id = mv.venture_id
WHERE mv.mission_id = $1
ORDER BY mv.created_at ASC
`

type ListMissionVenturesRow struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	MissionID   pgtype.UUID      `db:"mission_id" json:"mission_id"`
	VentureID   pgtype.UUID      `db:"venture_id" json:"venture_id"`
	Description string           `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	VentureName string           `db:"venture_name" json:"venture_name"`
}

func (q *Queries) ListMissionVentures(ctx context.Context, missionID pgtype.UUID) ([]ListMissionVenturesRow, error) {
	rows, err := q.db.Query(ctx, listMissionVentures, missionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMissionVenturesRow{}
	for rows.Next() {
		var i ListMissionVenturesRow
		if err := rows.Scan(
			&i.ID,
			&i.MissionID,
			&i.VentureID,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VentureName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
