// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MissionMemberRole string

const (
	MissionMemberRoleAdmin  MissionMemberRole = "admin"
	MissionMemberRoleMember MissionMemberRole = "member"
)

func (e *MissionMemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MissionMemberRole(s)
	case string:
		*e = MissionMemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MissionMemberRole: %T", src)
	}
	return nil
}

type NullMissionMemberRole struct {
	MissionMemberRole MissionMemberRole `json:"mission_member_role"`
	Valid             bool              `json:"valid"` // Valid is true if MissionMemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMissionMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MissionMemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MissionMemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMissionMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MissionMemberRole), nil
}

type MissionMember struct {
	ID        pgtype.UUID       `db:"id" json:"id"`
	MissionID pgtype.UUID       `db:"mission_id" json:"mission_id"`
	UserID    pgtype.UUID       `db:"user_id" json:"user_id"`
	Role      MissionMemberRole `db:"role" json:"role"`
	CreatedAt pgtype.Timestamp  `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp  `db:"updated_at" json:"updated_at"`
}

type MissionOrganization struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	Name        string           `db:"name" json:"name"`
	Description string           `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type MissionVenture struct {
	ID          pgtype.UUID      `db:"id" json:"id"`
	MissionID   pgtype.UUID      `db:"mission_id" json:"mission_id"`
	VentureID   pgtype.UUID      `db:"venture_id" json:"venture_id"`
	Description string           `db:"description" json:"description"`
	CreatedAt   pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type MissionVentureMember struct {
	ID               pgtype.UUID       `db:"id" json:"id"`
	MissionVentureID pgtype.UUID       `db:"mission_venture_id" json:"mission_venture_id"`
	MissionMemberID  pgtype.UUID       `db:"mission_member_id" json:"mission_member_id"`
	UserID           pgtype.UUID       `db:"user_id" json:"user_id"`
	Role             MissionMemberRole `db:"role" json:"role"`
	CreatedAt        pgtype.Timestamp  `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamp  `db:"updated_at" json:"updated_at"`
}

type User struct {
	ID             pgtype.UUID      `db:"id" json:"id"`
	Username       string           `db:"username" json:"username"`
	CreatedAt      pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at" json:"updated_at"`
	Email          string           `db:"email" json:"email"`
	HashedPassword string           `db:"hashed_password" json:"hashed_password"`
}

type Venture struct {
	ID              pgtype.UUID      `db:"id" json:"id"`
	Name            string           `db:"name" json:"name"`
	Description     string           `db:"description" json:"description"`
	CreatedByUserID pgtype.UUID      `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       pgtype.Timestamp `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamp `db:"updated_at" json:"updated_at"`
}

type VentureMember struct {
	ID        pgtype.UUID       `db:"id" json:"id"`
	VentureID pgtype.UUID       `db:"venture_id" json:"venture_id"`
	UserID    pgtype.UUID       `db:"user_id" json:"user_id"`
	Role      MissionMemberRole `db:"role" json:"role"`
	CreatedAt pgtype.Timestamp  `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamp  `db:"updated_at" json:"updated_at"`
}
